# Generated by Django 5.0.7 on 2024-09-30 23:01

import beauty_distributor.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la Categoría')),
                ('descripcion', models.TextField(verbose_name='Descripción de la Categoría')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la Marca')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la Presentación')),
                ('descripcion', models.TextField(verbose_name='Descripción de la Presentación')),
            ],
            options={
                'verbose_name': 'Presentación',
                'verbose_name_plural': 'Presentaciones',
            },
        ),
        migrations.CreateModel(
            name='CartaColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_color', models.CharField(max_length=50, verbose_name='Código de Color')),
                ('nombre_color', models.CharField(max_length=255, verbose_name='Nombre del Color')),
                ('hexadecimal', models.CharField(max_length=7, verbose_name='Código Hexadecimal')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción del Color')),
                ('marca', models.ForeignKey(default=beauty_distributor.models.CartaColor.default_marca, on_delete=django.db.models.deletion.CASCADE, related_name='cartas_colores', to='beauty_distributor.marca')),
            ],
            options={
                'verbose_name': 'Carta de Color',
                'verbose_name_plural': 'Cartas de Colores',
                'unique_together': {('codigo_color', 'marca')},
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Producto')),
                ('descripcion', models.TextField(default='Descripción no disponible', verbose_name='Descripción del Producto')),
                ('carta_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='beauty_distributor.cartacolor', verbose_name='Carta de Color')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='beauty_distributor.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='beauty_distributor.marca')),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='beauty_distributor.presentacion')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidades', models.PositiveIntegerField(default=0, verbose_name='Unidades')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='beauty_distributor.producto')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventarios',
                'unique_together': {('producto',)},
            },
        ),
    ]
