# Generated by Django 5.0.7 on 2024-10-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_distributor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio'),
        ),
    ]
