# Generated by Django 5.0.7 on 2024-10-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_distributor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='permite_color',
            field=models.BooleanField(default=False, verbose_name='¿Permite Carta de Colores?'),
        ),
    ]
